app/containers/Alarms/index.js, app/containers/App/components/ProtectedRouteWithLayout.js, app/containers/App/index.js, app/containers/Dashboard/index.js, app/graphql/queries.js
JIRA: [TW-754](https://connectustechnologies.atlassian.net/browse/TW-754)
*Created a minimal Dashboard with # of AP, client counts for June 30 TIP demo.*
=> Feature/TW-754: Minimal Dashboard June 30 demo #19

app/containers/Accounts/index.js, app/containers/ProfileDetails/index.js, app/containers/Profiles/index.js, app/graphql/mutations.js, app/index.js, package-lock.json, package.json
JIRA: [TW-606](https://connectustechnologies.atlassian.net/browse/TW-606)
finished Captive Portal Profile
=> Feature/tw 606: Captive Portal Profile

app/containers/Network/containers/AccessPointDetails/index.js, app/graphql/mutations.js
JIRA: [TW-472](https://connectustechnologies.atlassian.net/browse/TW-472)
*Updated Firmware Tab*
*
*
=> Feature/TW-472: Updated Firmware Tab

app/containers/App/index.js, app/containers/MasterLayout/index.js, app/containers/System/containers/Firmware/index.js, app/containers/System/containers/Manufacturer/index.js, app/containers/System/index.js, app/graphql/mutations.js, package-lock.json, package.json
JIRA: [TW-440](https://connectustechnologies.atlassian.net/browse/TW-440)
*Device Manufacturers that lets user search for OUI and update manufacturer alias*
*
*
=> Feature TW-440: Device Manufacturers

app/containers/Network/containers/AccessPointDetails/index.js, app/containers/Network/index.js, app/graphql/mutations.js
JIRA: [W-724](https://connectustechnologies.atlassian.net/browse/TW-724)
*Bind an Access Point to a customer based on the location*
*
*
=> Feature: TW-724: Add Access Point

app/containers/Dashboard/index.js, app/containers/MasterLayout/index.js, app/graphql/queries.js
JIRA: [TW-841](https://connectustechnologies.atlassian.net/browse/TW-841)
*combine Client 5Ghz counts, OS stats temperature change unit to C, Alarms count change to Navbar, fixed Dashboard UI*
*
*Screenshots of what it will look like after this PR 
*
=> Feature/TW-841: Marcel's Revised Changes

app/containers/System/containers/Firmware/index.js, app/graphql/mutations.js, app/graphql/queries.js
JIRA: [TW-439](https://connectustechnologies.atlassian.net/browse/TW-439)
*Systems firmware page that allows user to add/delete/edit track assignments and firmwares*
*
=> Feature/TW-439: System Firmware

app/containers/Dashboard/index.js, app/graphql/queries.js, package-lock.json, package.json
JIRA: [TW-843](https://connectustechnologies.atlassian.net/browse/TW-843)
*Added three Line Charts for Inservice APs (24hours), Client Devices (24hours) and Traffic (24hours)*
=> Feature/TW-843: Dashboard Three 24 hour graphs

app/containers/Network/containers/AccessPoints/index.js
JIRA: [TW-968](https://connectustechnologies.atlassian.net/browse/TW-968)
*Convert upTime in seconds to HH:MM:SS format*
*
*
=> hotfix/TW-968: seconds to hh:mm:ss format

app/containers/System/containers/BlockedList/index.js, app/containers/System/index.js, app/graphql/mutations.js, app/graphql/queries.js, package-lock.json, package.json
JIRA: [TW-957](https://connectustechnologies.atlassian.net/browse/TW-740)
Blocked list page that lets user to add and delete MACs*
*
=> feature/TW-957: Blocked List Page

app/containers/Dashboard/index.js
JIRA: [TW-843](https://connectustechnologies.atlassian.net/browse/TW-843)
*Updated line charts with polling new data after every 5 min*
=> Feature/TW-843-polling: Line charts with polling new data after an interval

Dockerfile, app/config.js, app/index.html, app/index.js, docker_entrypoint.sh, generate_config_js.sh, package-lock.json
JIRA: [TW-910](https://connectustechnologies.atlassian.net/browse/TW-910)
switched API URL to be dynamic based off of Docker run environment variable
=> Hotfix/docker: made API URL Dynamic 

app/containers/Profiles/index.js
Added Equipment Count values for Profiles table
*
*
*Screenshots of what it will look like after this PR 
*
=> hotfix/WIFI-584: Added Equipment Count

app/containers/Network/containers/AccessPointDetails/index.js
*Summary of this PR  Updated firmware query for Access Point firmware*
=> hotfix/WIFI-571: updated firmware query

app/containers/ProfileDetails/index.js
JIRA: [TW-975](https://connectustechnologies.atlassian.net/browse/TW-975)
User List and Radius Authentication functionality for Captive Portal Form*
*
*
=> Feature/TW-975: Captive User List & Radius

app/containers/Profiles/index.js
JIRA: [WIFI-590](https://telecominfraproject.atlassian.net/browse/WIFI-590)
Reload profile list when a profile is deleted.
N/A
N/A
=> hotfix/WIFI-590: Reload profiles when one is deleted

app/containers/Login/index.js
JIRA: [WIFI-588](https://telecominfraproject.atlassian.net/browse/WIFI-588)
Error flashes on login because when we authenticate the user we reset the store. This causes issues because we load the dashboard at the same time and the store is reset in the middle of the request and returns errors.
*Screenshots of what it looked like after this PR*
=> hotfix/WIFI-588: Error on login

app/containers/Network/containers/AccessPointDetails/index.js
Removed .toLowerCase() on firmware query for AP details*
=> hotfix/WIFI-612: Fixed Firmware Query on AP Details 

app/containers/AddProfile/index.js, app/containers/Network/containers/AccessPointDetails/index.js, app/containers/Network/index.js, app/containers/ProfileDetails/index.js, app/graphql/queries.js
Added pagination for select dropdowns*
=> hotfix/Pagination: Pagination for profiles query

app/containers/Network/containers/AccessPoints/index.js, app/containers/Network/containers/AccessPoints/index.module.scss
JIRA: [WIFI-708](https://telecominfraproject.atlassian.net/browse/WIFI-708)
Modified Access Points table to have default values where devices default value will be 0 and other string values will be N/A
=> Hotfix/wifi 708: Added default values to the Access Points table

app/containers/Network/containers/AccessPoints/index.js, app/graphql/queries.js
JIRA: [WIFI-613](https://telecominfraproject.atlassian.net/browse/WIFI-613)
Added firmware Version column to Access Points Table
=> Feature/wifi 613 Added Firmware Version to AP Table

app/containers/Network/containers/AccessPointDetails/index.js
JIRA: [WIFI-758](https://telecominfraproject.atlassian.net/browse/WIFI-758)
Fixed data path for updateEquipmentFirmware so when Download, Flash, Update button is clicked the proper success notification is shown
=> WIFI-758: Fixed data path for updateEquipmentFirmware

app/containers/Network/containers/AccessPointDetails/index.js, app/graphql/mutations.js, package-lock.json, package.json
JIRA: [WIFI-817](https://telecominfraproject.atlassian.net/browse/WIFI-817)
Added GraphQL for Switch to Inactive Bank, and Reboot AP
=> Feature/wifi 817: Switch to Inactive Bank, and Reboot AP

.github/workflows/dockerpublish.yml, Dockerfile, app/commit.properties
JIRA: [WIFI-846](https://telecominfraproject.atlassian.net/jira/software/c/projects/WIFI/issues/WIFI-846?jql=project%20%3D%20%22WIFI%22%20AND%20%28text%20~%20%22846%22%20OR%20issuekey%3D%22WIFI-846%22%29%20%20ORDER%20BY%20created%20DESC)
A property file with commit hash and version will be added to the container's directory during the build. This file would be used to aid in the troubleshooting of microservices
Before PR
After PR
=> WIFI 846: docker cron schedule

app/containers/Network/containers/ClientDevices/index.js, app/graphql/queries.js, package-lock.json
JIRA: [WIFI-1012](https://telecominfraproject.atlassian.net/jira/software/c/projects/WIFI/issues/WIFI-1012)
Added support for device status in the network table. 
=> feature/WIFI-1012: Added client device status support

app/containers/Profiles/index.js
JIRA: [WIFI-735](https://telecominfraproject.atlassian.net/browse/WIFI-735)
When refetch was called it would only refetch the first page of data, which would not update the cache of paginated data. By passing the initial variables on refetch will reset the cursor based pagination and clear the cache.
=> hotfix/WIFI-735: fixed profiles refetch

app/containers/Network/containers/AccessPointDetails/index.js
Added a delete equipment method to delete access points
=> Hotfix/WIFI-640: Added delete button 

app/constants/index.js, app/containers/App/index.js, app/containers/Dashboard/index.js, app/containers/Network/containers/ClientDevices/index.js
JIRA: [NETEXP-750](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=NETEXP-750&assignee=5f91b571f162650070d4dc94)
Added radioType label constant mapping
=> hotfix/NETEXP-750: Friendly Radio Names

app/containers/System/containers/Firmware/index.js
JIRA: [NETEXP-558](https://connectustechnologies.atlassian.net/secure/RapidBoard.jspa?rapidView=11&modal=detail&selectedIssue=NETEXP-558&assignee=5f91b571f162650070d4dc94)
Firmware version modal dropdown displays the added the newly added version without having to refresh the page
=> hotfix/NETEXP-558: Auto updates firmware version 

app/containers/AddProfile/index.js, app/containers/ProfileDetails/index.js, app/graphql/functions.js, package-lock.json, package.json
Fixed prop names to make them compliant with NETEXP-989
=> hotfix/ProfilePages: fixed prop names

app/containers/Network/containers/BulkEditAccessPoints/index.js, app/containers/Network/containers/BulkEditAccessPoints/index.module.scss
JIRA: [WIFI-1442](https://telecominfraproject.atlassian.net/browse/WIFI-1442)
-Added null-checks for cases where the AP is not configured and certain fields do not exist
-Fixed the property path for SNR drop% and Min Load to match the data model 
=> Bugfix/WIFI-1442: Bulk-Edit APs Page Fixes

.github/workflows/dockerpublish.yml
Build trigger for release to enabled by Opsfleet
=> WIFI:1669 TIP 1.0 Update SDK components  in release 1.0 branch

app/containers/Network/containers/AccessPointDetails/index.js, app/containers/Network/containers/BulkEditAccessPoints/index.js, app/graphql/mutations.js, app/graphql/queries.js
WIFI-1505: https://telecominfraproject.atlassian.net/browse/WIFI-1505
Description
Summary of this PR
-Added editing for manual backup channel in Bulk-Edit-Access-Points page
-Added field for Channel status in graphql query
-Cleanup gql queries/mutations for Access Point Details page
Before this PR
Screenshots of what it looked like before this PR
After this PR
Screenshots of what it will look like after this PR
=> hotfix/WIFI-1505: Manual Channel Editing

app/containers/ProfileDetails/index.js
JIRA: [WIFI-824](https://telecominfraproject.atlassian.net/browse/WIFI-824)
Added file downloading functionality for the Captive Portal page. 
=> bugfix/WIFI-824: File downloading functionality for Captive Portal Page

app/containers/App/index.js, app/containers/MasterLayout/index.js
JIRA: [WIFI-1452](https://telecominfraproject.atlassian.net/browse/WIFI-1452)
Fixed bug on Edit User page that prevents access of the Edit User page when the user id is 0. 
=> bugfix/WIFI-1452: Fixed bug on Edit User page

app/containers/ProfileDetails/index.js
JIRA: [NETEXP-1335](https://connectustechnologies.atlassian.net/browse/NETEXP-1335)
Added `associatedSsidProfiles` field in GetProfile query used for Passpoint profile
=> bugfix/NETEXP-1335: Added associatedSsidProfiles field in GetProfile query

app/containers/System/containers/AutoProvision/index.js
JIRA: [NETEXP-1399](https://connectustechnologies.atlassian.net/browse/NETEXP-1399)
Added Pagination for AP select in Auto-Provision page
=> bugfix/NETEXP-1399: Added Pagination for AP select in Auto-Provision page

.github/workflows/dockerpublish.yml
JIRA: [2026](https://telecominfraproject.atlassian.net/browse/WIFI-2026)
=> WIFI-2026 Change docker tags from 0.0.1-SNAPSHOT to 1.1.0-SNAPSHOT

app/containers/Network/containers/AccessPointDetails/index.js
Fixed fetchPolicy condition for AP details `GET_ALL_PROFILES` query so that stale data would not persist in Select Dropdown. 
=> bugfix/WIFI-1846: Fixed fetchPolicy for AP details profile dropdown

app/containers/Dashboard/index.js, package-lock.json, package.json
[WIFI-1917](https://telecominfraproject.atlassian.net/browse/WIFI-1917)
_Thurs, April 1_
- Redo the structure of the dashboard data to be compatible with the library changes
=> WIFI-1917: Make compatible with recharts

app/containers/AddProfile/index.js
NO-JIRA
Added the file-uploading function to Add-Profile component (currently files cannot be uploaded when a profile is added, only on the edit page)
=> hotfix/AddProfileFileUpload: Added file uploading to Add Profile

app/constants/index.js
NO-JIRA
Changed sort order for Radios
=> hotfix/ApRadiosOrder: Changed USER_FRIENDLY_RADIOS order

app/styles/index.scss
NO-JIRA
Fixed Autofill Styling
=> hotfix/AutofillCss: Fixed autofill styling

app/containers/Dashboard/index.js
NOJIRA
- Restructure dashboard data for better compatibility with Recharts. 
- This gets rid of minor bugs
- Dependent on https://github.com/Telecominfraproject/wlan-cloud-ui-library/pull/299
No visual change
=> Bugfix/NOJIRA: Restructure Dashboard Data

app/containers/Network/containers/BulkEditAccessPoints/index.js
NO-JIRA
- Added allowedChannels field to validate channel inputs
- Cleaned up file to improve readability
=> hotfix/BulkEditAllowedChannels: Added allowedChannels field to BulkEditTable

app/containers/Network/containers/BulkEditAccessPoints/index.js, app/containers/System/containers/AutoProvision/index.js, app/utils/locations.js
NO-JIRA
- Restructured Location Data to allow hierarchical view in Auto-Provision Select  
- Made separate `utils` file for location functions for better readability
=> hotfix/AutoProvisionLocation: Changed location data structure for Auto-Provision
